spring:
  application:
    name: phishme_backend
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 9000

app:
  encryption:
    key: ${AES_ENCRYPTION_KEY}
  profanity:
    key: ${PROFANITY_API_KEY}

jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION} # 6 hours
  refresh-expiration: ${JWT_REFRESH_EXPIRATION} # 1 month

oidc:
  kakao-client-id: ${KAKAO_CLIENT_ID}
  apple-client-id: ${APPLE_CLIENT_ID}
  google-ios-client-id: ${GOOGLE_IOS_CLIENT_ID}
  google-android-client-id: ${GOOGLE_ANDROID_CLIENT_ID}
